### ISSUE TITLE
Incompatible types: 'Dynamic array' and 'Pointer'

### ISSUE THREAD

**Issue by cgramirez** [pult/libssh2_delphi#1]
In module: uMySFTPClient.pas
Line:StoredFingerprint := FHashMgr.GetFingerprint(FHost, FPort);
Error:
[dcc32 Error] uMySFTPClient.pas(1103): E2010 Incompatible types: 'Dynamic array' and 'Pointer'

Delphi 10.2 Berlin.

**Comment by pult** [comment]
[Fixed](https://github.com/pult/libssh2_delphi/commit/1d044fa8825f09b5da77558586db68935c6f892d)
