### ISSUE TITLE
Does it support Socks5 proxy?

### ISSUE THREAD

**Issue by edwinyzh** [pult/libssh2_delphi#12]
Thanks to the original author and @pult  for improving this library!

Does the SFTP component support connecting through Socks5 proxy? If yes, how?

Thank you!

**Comment by pult** [comment]
it is only wrapper for libssh2.

**Comment by pult** [comment]
Alternative: A dynamic link library with Delphi and C++ bindings based on PuTTY (https://github.com/superflexible/TGPuttyLib)

**Comment by edwinyzh** [comment]
> it is only wrapper for libssh2.

I know. A google search doesn't reveal that it supports socks5 proxy though.

Yes, TGPuttyLib is great!
