### ISSUE TITLE
Could not load library "libssh2.dll"

### ISSUE THREAD

**Issue by cgramirez** [pult/libssh2_delphi#2]
Delphi 10.2
When executing the demo, the following error appears:

First chance exception at $744908B2. Exception class ELoadLibrary with message 'Could not load library "libssh2.dll"'. Process Project1.exe (15488)

**Comment by pult** [comment]
libssh2_dll_x86x64.txt
need update "libssh2.dll , libeay32.dll , ssleay32.dll"

**x86:**
https://github.com/pult/libssh2_delphi/tree/master/bin
libssh2.dll.x86.7z
or
libssh2-1.8.0-vc11-x86.zip          http://windows.php.net/downloads/php-sdk/deps/vc11/x86/
openssl-1.0.2m-i386-win32.zip   http://indy.fulgan.com/SSL/

**x64:**
https://github.com/pult/libssh2_delphi/tree/master/bin/x64
libssh2.dll.x64.7z
or
libssh2-1.8.0-vc11-x64.zip              http://windows.php.net/downloads/php-sdk/deps/vc11/x64/
openssl-1.0.2m-x64_86-win64.zip  http://indy.fulgan.com/SSL/
