### ISSUE TITLE
Sorry, but why len=(Length(sth) - 1)

### ISSUE THREAD

**Issue by Rockstein2** [pult/libssh2_delphi#3]
why in libssh2.pas length = length (string)-1. I had to remove "1"
For Example
`
libssh2_channel_open_ex(session, SSession, Length(SSession) - 1, ...);
libssh2_channel_process_startup(channel, 'shell', Length('shell') - 1, nil, 0);
`

**Comment by pult** [comment]
Thanks!. Fixed: https://github.com/pult/libssh2_delphi/commit/55047384c0b1cf79fc3dd2f8e93438ec3abd35af

**Comment by Rockstein2** [comment]
Спасибо за оперативность! Странно, что никто до меня не юзал pty канал. Наверное все как sftp используют.

**Comment by pult** [comment]
Thanks 2!
Fixed https://github.com/pult/libssh2_delphi/commit/26f8d1bbdd711bb525067c33e61cc8688791bc0f by your comment https://github.com/pult/libssh2_delphi/commit/55047384c0b1cf79fc3dd2f8e93438ec3abd35af
